### ISSUE TITLE
Does this support Linux?

### ISSUE THREAD

**Issue by tschf** [diesire/atom-oracle-format#4]
Looks like this is possibly unsupported on Linux?

Looking in the bin directory, I do see `sdcli`, however it looks like it's just a luncher for sql developer:

```
# cat sdcli
#!/bin/bash

#=============================================================================
#  Launcher for Oracle SQL Developer
#  Copyright (c) 2005, Oracle. All rights reserved.
#=============================================================================

. "sqldeveloper"

#-----------------------------------------------------------------------------
#  product-specific function overrides
#-----------------------------------------------------------------------------
GetFullProductName()
{
    echo "Oracle SQL Developer"
}

GetShortProductName()
{
    echo "SQL Developer"
}
```

**Comment by diesire** [comment]
Only tested on Windows 7 with Oracle SQL Developer v4.0.3.

I don't have any Linux box with SQL Developer installed so I can't check it but I made a quick research and everything should be OK in Linux, just add `sdcli` [with the full path](https://community.oracle.com/thread/3727292?start=0&tstart=0) to the settings section

If that fails, run `sdcli`with the full path from the console to check if its available and working
