### ISSUE TITLE
Extend the grammar condition

### ISSUE THREAD

**Issue by tschf** [diesire/atom-oracle-format#5]
I notice you are using the generic SQL grammar to determine if this should run - https://github.com/diesire/atom-oracle-format/blob/master/lib/oracle-format.coffee#L30-L32

``` coffee
if editor.getGrammar().scopeName isnt 'source.sql'
  console.log 'This is not an SQL file'
  return
```

Not sure if you are aware, but there's also an Oracle specific grammar. See: https://atom.io/packages/language-oracle

**Comment by diesire** [comment]
Thanks for your feedback.

Just released v0.3.3 with plsql.oracle grammar support
